### ISSUE TITLE
Width issues when using label option

### ISSUE THREAD

**Issue by timbru31** [tkuhn/bchart#2]
Hi Tobias,

first of all, thanks a lot for this package! :)
However, I've got some issues using the width option alongside with the labels. My goal is to have the width of the diagram equal to the \textwidth, but it seems the label options are on top of the width, see example below:

```tex
\begin{figure}
	\begin{bchart}[min=5, max=55, step=10, unit=\%, width=\textwidth]
		\bcbar[label=All passwords, color=red]{7}
		\medskip
		\bcbar[label=Most of the passwords, color=red]{20}
		\medskip
		\bcbar[label=Some passwords, color=red]{45}
		\bigskip
		\bcbar[label=Don't know, color=yellow]{7}
		\bigskip
		\bcbar[label=None of the passwords, color=green!50]{20}
	\end{bchart}
	\caption{Percentage of password re-usage in the United States in 2018}
	\label{fig:us-password-reuse}
\end{figure}
```

Renders:

![Screenshot 2019-08-30 at 12 22 02](https://user-images.githubusercontent.com/838003/64013744-0a0c3c00-cb10-11e9-90b8-c0fafc390bdd.png)

---

Am I missing an option or have an error in reasoning? (current workaround is to use `width=.65\textwidth` but if I change the labels again, I need to figure out the width again.

Thanks,
Tim

**Comment by tkuhn** [comment]
Hi Tim,

Yes, the `width` argument is only about the part with the bars and is not considering the labels. The precise behavior you would like to have is probably hard to achieve. Using something like `width=.65\textwidth` is probably the best work-around.

Regards,
Tobias

**Comment by timbru31** [comment]
Alright, I can live with that :) - closing
